### ISSUE TITLE
sst deploy hangs forever in ci

### ISSUE THREAD

**Issue by ciiqr** [sst/ion#596]
I deployed a new app with sst ion from my local machine, it deployed fine, however now that I'm trying to get it deploying through ci (github actions) I've run into a bit of an issue. The app deploys successfully (I can see my changes), however the command hangs forever and never actually exits. I enabled verbose logging and can see that it gets to "unlocking", but never progresses past that point (without verbose logging, nothing is ever printed). Full logs included below.

I followed the [old docs](https://docs.sst.dev/going-to-production#deploy-from-github-actions) for setting up OIDC & creating the role (thus have used a `GitHub` role with `AdministratorAccess` for now), and given the deployment is being updated it would seem that's working fine.

Additionally I tried running `sst unlock --stage=sandbox --verbose` in ci, and that works fine, it's just the deploy command that hangs.

Here's the action:
```yaml
name: deploy-sandbox
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}
jobs:
  deploy-sandbox:
    name: Deploy Sandbox
    runs-on: ubuntu-latest
    permissions:
      # required for aws-actions/configure-aws-credentials
      id-token: write
      # required for actions/checkout
      contents: read
    steps:
      - uses: actions/checkout@v4

      # setup node
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      # install sst
      - name: Install SST
        run: curl -fsSL https://ion.sst.dev/install | bash

      # configure aws credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<redacted>:role/GitHub
          aws-region: us-east-1

      # TODO: debug
      # - name: DEBUG
      #   run: sst unlock --stage=sandbox --verbose

      # deploy
      - name: Deploy
        run: sst deploy --stage=sandbox --verbose
        # TODO: DEBUG
        timeout-minutes: 30
```

the sst config:
```ts
/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
    app(input) {
        return {
            name: "core-app",
            removal: input?.stage === "production" ? "retain" : "remove",
            home: "aws",
        };
    },
    async run() {
        new sst.aws.Nextjs("<redacted>");
    },
});
```

and the full deploy logs `sst deploy --stage=sandbox --verbose`:
```
time=2024-06-25T14:00:42.726Z level=INFO msg="checking for pulumi" path=/home/runner/.config/sst/bin/pulumi
time=2024-06-25T14:00:42.905Z level=INFO msg="checking for bun" path=/home/runner/.config/sst/bin/bun
time=2024-06-25T14:00:42.909Z level=INFO msg="initializing project" version=0.0.441
time=2024-06-25T14:00:42.9[10](https://github.com/<redacted>/core-app/actions/runs/9663868285/job/26657142993#step:8:11)Z level=INFO msg="esbuild building"
time=2024-06-25T14:00:42.912Z level=INFO msg="esbuild built" outfile=/home/runner/work/core-app/core-app/.sst/eval/eval-1719324042910.mjs
time=2024-06-25T14:00:42.912Z level=INFO msg="evaluating config"
time=2024-06-25T14:00:42.945Z level=INFO msg="config evaluated"
time=2024-06-25T14:00:42.945Z level=INFO msg="checking platform"
time=2024-06-25T[14](https://github.com/<redacted>/core-app/actions/runs/9663868285/job/26657142993#step:8:15):00:42.945Z level=INFO msg="checking provider" name=aws version=latest compare=latest
time=2024-06-25T14:00:42.946Z level=INFO msg="credentials found"
time=2024-06-25T14:00:42.946Z level=INFO msg="fetching bootstrap"
time=2024-06-25T14:00:43.269Z level=INFO msg="found existing bootstrap" data="{\"version\":1,\"asset\":\"sst-asset-<redacted>\",\"state\":\"sst-state-<redacted>\"}"
time=2024-06-25T14:00:43.270Z level=INFO msg="loaded config" app=core-app stage=sandbox
time=2024-06-25T14:00:43.270Z level=INFO msg="running stack command" cmd=deploy
time=2024-06-25T14:00:43.270Z level=INFO msg="INFO locking app=core-app stage=sandbox"
time=2024-06-25T14:00:43.270Z level=INFO msg="INFO getting data key=lock app=core-app stage=sandbox"
time=2024-06-25T14:00:43.521Z level=INFO msg="INFO putting data key=lock app=core-app stage=sandbox"
time=2024-06-25T14:00:43.772Z level=INFO msg="INFO pulling state app=core-app stage=sandbox out=/home/runner/work/core-app/core-app/.sst/.pulumi/stacks/core-app/sandbox.json"
time=2024-06-25T14:00:44.425Z level=INFO msg="INFO getting passphrase app=core-app stage=sandbox"
time=2024-06-25T14:00:44.764Z level=INFO msg="INFO getting data key=secret app=core-app stage=sandbox"
time=2024-06-25T14:00:45.022Z level=INFO msg="INFO getting passphrase app=core-app stage=sandbox"
time=2024-06-25T14:00:45.346Z level=INFO msg="esbuild building"
time=2024-06-25T14:00:45.443Z level=INFO msg="esbuild built" outfile=/home/runner/work/core-app/core-app/.sst/platform/eval/eval-[17](https://github.com/<redacted>/core-app/actions/runs/9663868285/job/26657142993#step:8:18)19324045346.mjs
time=2024-06-25T14:00:45.443Z level=INFO msg="tracked files"
time=2024-06-25T14:00:45.586Z level=INFO msg="built workspace"
time=2024-06-25T14:00:45.762Z level=INFO msg="built stack"
time=2024-06-25T14:00:45.901Z level=INFO msg="built config"
time=[20](https://github.com/<redacted>/core-app/actions/runs/9663868285/job/26657142993#step:8:21)24-06-25T14:00:45.901Z level=INFO msg="running stack command" cmd=deploy
time=2024-06-25T14:02:00.562Z level=INFO msg="done running stack command"
time=2024-06-25T14:02:00.562Z level=INFO msg="INFO putting summary app=core-app stage=sandbox"
time=2024-06-25T14:02:00.562Z level=INFO msg="INFO putting data key=summary app=core-app stage=sandbox/ggyc99ffkpmiwk5kpimg17jy"
time=2024-06-25T14:02:00.846Z level=INFO msg="stack command complete"
time=2024-06-25T14:02:01.[22](https://github.com/<redacted>/core-app/actions/runs/9663868285/job/26657142993#step:8:23)5Z level=INFO msg="INFO putting links app=core-app stage=sandbox"
time=2024-06-25T14:02:01.225Z level=INFO msg="INFO putting data key=link app=core-app stage=sandbox"
time=20[24](https://github.com/<redacted>/core-app/actions/runs/9663868285/job/26657142993#step:8:25)-06-25T14:02:01.225Z level=INFO msg="INFO getting passphrase app=core-app stage=sandbox"
time=2024-06-[25](https://github.com/<redacted>/core-app/actions/runs/9663868285/job/26657142993#step:8:26)T14:02:01.861Z level=INFO msg="INFO pushing state app=core-app stage=sandbox from=/home/runner/work/core-app/core-app/.sst/.pulumi/stacks/core-app/sandbox.json"
time=2024-06-25T14:02:02.577Z level=INFO msg="INFO unlocking app=core-app stage=sandbox"
Error: The action 'Deploy' has timed out after 30 minutes.
```
